"""Training configuration for XLM-RoBERTa smishing classification."""

from __future__ import annotations

import dataclasses
import json
import os
from dataclasses import dataclass, field
from typing import Dict

#: Optional per-run settings file. The Colab package for a variant carries one,
#: so the uploaded zip alone determines how that run trains.
OVERRIDES_FILE = "training_overrides.json"

# Three-way training head, ordered benign -> severe. These are the *dataset*
# labels the model is trained to predict; the user-facing buckets (Safe /
# Unknown / Spam / Blocked) are derived from these at routing time — see
# ai/service/classifier.py:route and ai/datasets/LABELING_GUIDE.md.
ID2LABEL: Dict[int, str] = {0: "Ham", 1: "Spam", 2: "Scam"}
LABEL2ID: Dict[str, int] = {v: k for k, v in ID2LABEL.items()}

#: Column naming where a row came from, carried by the retraining snapshot and
#: by ``scripts/augment_scam_dataset.py`` output.
ORIGIN_COLUMN = "origin"

#: Origins whose rows are synthetic: generated by
#: ``scripts/augment_scam_dataset.py`` rather than received by a real phone.
#:
#: These are kept **out of the validation split** (see
#: ``training/dataset.py:load_split``). A model trained on generated text
#: classifies more generated text from the same templates easily, while the
#: incumbent it is compared against has never seen any -- so letting synthetic
#: rows into validation would credit the candidate for learning our writing
#: style and report it as a scam-detection gain. That is precisely the number
#: the promotion gate exists to protect (``retraining/promotion.py``), and the
#: frozen holdout cannot catch it because the holdout is only consulted later.
SYNTHETIC_ORIGINS = frozenset({"authored", "variant"})


@dataclass
class TrainingConfig:
    # Base model: XLM-RoBERTa uses a SentencePiece tokenizer with a ~250K
    # (250,002) shared multilingual vocabulary — covers Tagalog/English/Taglish
    # out of the box, which is why it was chosen over English-only encoders.
    model_name: str = "xlm-roberta-base"
    num_labels: int = 3
    id2label: Dict[int, str] = field(default_factory=lambda: dict(ID2LABEL))
    label2id: Dict[str, int] = field(default_factory=lambda: dict(LABEL2ID))

    # Data
    dataset_path: str = "datasets/labeled"
    text_column: str = "text"
    label_column: str = "label"
    test_size: float = 0.20  # 80/20 train/validation split
    seed: int = 42

    # Tokenization
    max_length: int = 128

    # Optimization (AdamW is the HuggingFace Trainer default optimizer).
    learning_rate: float = 2e-5
    weight_decay: float = 0.01
    train_batch_size: int = 16
    eval_batch_size: int = 32
    num_epochs: int = 4
    warmup_ratio: float = 0.1

    # Class-weighted loss. The dataset is ~62% Ham / 21% Spam / 17% Scam, so an
    # unweighted model is rewarded for guessing Ham whenever it is unsure --
    # Ham errors dominate the loss simply by being more numerous. Weighting
    # each class by ``n_samples / (n_classes * class_count)`` makes a Scam
    # mistake cost roughly 3.5x a Ham mistake, which raises Scam recall (the
    # class that matters most: a missed scam defrauds a user, a misfiled promo
    # annoys them) at a small cost to Ham precision. Macro-F1 is the metric
    # this is meant to improve; raw accuracy may dip slightly.
    #
    # Set False to train with the standard unweighted cross-entropy.
    class_weighted_loss: bool = True

    # Strength of that weighting, as an exponent on the inverse-frequency
    # weights: 1.0 = full inverse frequency (default, unchanged behaviour),
    # 0.5 = square root (softer), 0.0 = no weighting. Added 2026-09-21: on the
    # real-only corpus, full weighting makes a Scam mistake cost ~6x a Ham
    # mistake, and every model retrained since flagged 11-14 legitimate holdout
    # messages as Scam against 5 for the live model. 0.5 (~2.5x) is variant C.
    class_weight_power: float = 1.0

    # Output
    output_dir: str = "models/xlm-roberta-smishing"


def load_config(path: str = OVERRIDES_FILE) -> TrainingConfig:
    """``TrainingConfig``, with fields overridden by ``path`` when it exists.

    Unknown keys raise instead of being ignored: a misspelt setting would
    otherwise train silently with the default and report it as the variant.
    """
    config = TrainingConfig()
    if not os.path.isfile(path):
        return config
    with open(path, encoding="utf-8") as handle:
        overrides = json.load(handle)
    known = {f.name for f in dataclasses.fields(TrainingConfig)}
    unknown = sorted(set(overrides) - known)
    if unknown:
        raise ValueError(f"{path}: unknown training setting(s) {unknown}")
    return dataclasses.replace(config, **overrides)
