"""Model version registry client (Sprint 4, WBS 4.4.3).

``register()`` / ``activate()`` talk to the backend's ``ModelVersion`` API
(WBS 4.3.4) so a retraining run's candidate becomes something ``ModelVersions``
can track -- without ever swapping the live checkpoint. That swap stays a
deliberate, separate act; see the "Nothing here swaps the live model" note in
``scripts/retrain.py`` and the promotion-invalidates-campaign-centroids
warning in ``RETRAINING.md`` § Rollback.

Two flags gate this from the CLI (``scripts/retrain.py --register`` /
``--activate``), not one: registering the candidate as an **inactive**
``ModelVersion`` row is safe the moment a gate verdict exists -- it is just a
record. *Activating* it is the step that needs a human (currently: the
adviser, per the open item in ``PIPELINE.md`` § Stage 5b) to sign off on. A
pipeline that auto-swaps on a green gate is exactly the failure mode that
note warns against.

Mirrors ``reports.DatabaseReportSource``'s HTTP shape deliberately -- same
``urllib.request.Request`` + ``x-api-key`` header, same "failures raise"
policy, same hint on a 401. Two independent re-implementations of the same
handful of lines is one more place for the auth header to go missing
unnoticed, which is exactly how ``centroid_source.py``'s missing header
survived until WBS 4.3.5 found it.

Also used read-only from the *service* side (``service/main.py``'s startup
version check calls :meth:`ModelRegistry.get_active`) -- one HTTP client for
all of ``/models``, rather than a second copy of this plumbing over there.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Optional


class ModelRegistryError(RuntimeError):
    """The backend's ``/models`` API could not be reached, or refused the request.

    Raised rather than swallowed, for the same reason
    :class:`reports.ReportSourceError` raises: a registration or activation
    that silently no-ops is worse than one that fails loudly. A run that
    printed "registered" while ``ModelVersions`` has no matching row is a
    harder bug to notice than one that stopped the run outright.
    """


class ModelRegistry:
    """Talks to the backend's ``ModelVersion`` routes (WBS 4.3.4)."""

    def __init__(self, base_url: str, api_key: str, timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.timeout = timeout

    def _call(self, path: str, method: str, payload: Optional[dict] = None) -> Optional[dict]:
        """One HTTP call, decoded. Every failure mode becomes ``ModelRegistryError``."""
        url = f"{self.base_url}{path}"
        headers = {"x-api-key": self.api_key}
        data = None
        if method == "POST":
            data = json.dumps(payload or {}).encode("utf-8")
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(url, data=data, method=method, headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as resp:  # noqa: S310
                body = resp.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            hint = ""
            if exc.code == 401:
                hint = " -- BANTAI_AI_BACKEND_API_KEY is missing or does not match the backend's INTERNAL_API_KEY"
            elif exc.code == 409:
                hint = " -- a ModelVersion with this versionTag is already registered"
            raise ModelRegistryError(f"{method} {url} returned HTTP {exc.code} {exc.reason}{hint}") from exc
        except urllib.error.URLError as exc:
            raise ModelRegistryError(f"{method} {url} failed: {exc.reason}. Is the backend running?") from exc

        if not body:
            return None
        try:
            return json.loads(body)
        except json.JSONDecodeError as exc:
            raise ModelRegistryError(f"{method} {url} did not return JSON: {exc}") from exc

    def register(
        self,
        version_tag: str,
        f1_score: float,
        accuracy: Optional[float] = None,
        notes: Optional[str] = None,
    ) -> str:
        """``POST /models``. Registers the candidate **inactive**; returns its id.

        ``version_tag`` is ``@unique`` on the backend (see
        ``backend/database/prisma/schema.prisma``, whose comment on
        ``ModelVersion`` says the tag is "auto-generated by AI service") -- so
        this side owns the format. ``pipeline.py`` uses ``v<run-stamp>``,
        e.g. ``v2026-08-17T04-15-33Z``, so a version tag always points back to
        the run directory it came from.
        """
        payload = {"versionTag": version_tag, "f1Score": f1_score}
        if accuracy is not None:
            payload["accuracy"] = accuracy
        if notes is not None:
            payload["notes"] = notes
        result = self._call("/models", "POST", payload)
        model_id = (result or {}).get("id")
        if not model_id:
            raise ModelRegistryError(f"POST {self.base_url}/models did not return an id: {result!r}")
        return model_id

    def activate(self, model_id: str) -> None:
        """``POST /models/:id/activate``. The deliberate, separate promotion step.

        Deactivates whatever was active and activates this row -- see
        ``ModelsService.promote`` on the backend. Calling this is the human
        act this whole module exists to keep separate from a green gate.
        """
        self._call(f"/models/{model_id}/activate", "POST")

    def get_active(self) -> Optional[dict]:
        """``GET /models/active``. ``None`` when no model has ever been registered.

        Read-only counterpart used by ``service/main.py``'s startup check --
        comparing what the backend thinks is live against the ``version_tag``
        this service is actually serving (``models/<dir>/version.json``).
        """
        return self._call("/models/active", "GET")
