"""Model version registry client (Sprint 4, WBS 4.4.3).

``register()`` / ``activate()`` talk to the backend's ``ModelVersion`` API
(WBS 4.3.4) so a retraining run's candidate becomes something ``ModelVersions``
can track -- without ever swapping the live checkpoint. That swap stays a
deliberate, separate act; see the "Nothing here swaps the live model" note in
``scripts/retrain.py`` and the promotion-invalidates-campaign-centroids
warning in ``RETRAINING.md`` § Rollback.

Two flags gate this from the CLI (``scripts/retrain.py --register`` /
``--activate``), not one: registering the candidate as an **inactive**
``ModelVersion`` row is safe the moment a gate verdict exists -- it is just a
record. *Activating* it is the step that needs a human (currently: the
adviser, per the open item in ``PIPELINE.md`` § Stage 5b) to sign off on. A
pipeline that auto-swaps on a green gate is exactly the failure mode that
note warns against.

Mirrors ``reports.DatabaseReportSource``'s HTTP shape deliberately -- same
``urllib.request.Request`` + ``x-api-key`` header, same "failures raise"
policy, same hint on a 401. Two independent re-implementations of the same
handful of lines is one more place for the auth header to go missing
unnoticed, which is exactly how ``centroid_source.py``'s missing header
survived until WBS 4.3.5 found it.

Also used read-only from the *service* side (``service/main.py``'s startup
version check calls :meth:`ModelRegistry.get_active`) -- one HTTP client for
all of ``/models``, rather than a second copy of this plumbing over there.
"""

from __future__ import annotations

import json
import re
import urllib.error
import urllib.request
from typing import Any, Dict, Optional, Tuple

from .checksum import bundle_digest, hash_bundle
from .version_file import read_version

#: The classifier's classes, in the order the backend's evidence check reads.
EVIDENCE_CLASSES = ("Ham", "Spam", "Scam")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


class ModelRegistryError(RuntimeError):
    """The backend's ``/models`` API could not be reached, or refused the request.

    Raised rather than swallowed, for the same reason
    :class:`reports.ReportSourceError` raises: a registration or activation
    that silently no-ops is worse than one that fails loudly. A run that
    printed "registered" while ``ModelVersions`` has no matching row is a
    harder bug to notice than one that stopped the run outright.
    """


class ModelRegistry:
    """Talks to the backend's ``ModelVersion`` routes (WBS 4.3.4)."""

    def __init__(self, base_url: str, api_key: str, timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.timeout = timeout

    def _call(self, path: str, method: str, payload: Optional[dict] = None) -> Optional[dict]:
        """One HTTP call, decoded. Every failure mode becomes ``ModelRegistryError``."""
        url = f"{self.base_url}{path}"
        headers = {"x-api-key": self.api_key}
        data = None
        if method == "POST":
            data = json.dumps(payload or {}).encode("utf-8")
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(url, data=data, method=method, headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as resp:  # noqa: S310
                body = resp.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            hint = ""
            if exc.code == 401:
                hint = " -- BANTAI_AI_MODELS_API_KEY is missing or does not match AI_MODELS_API_KEY"
            elif exc.code == 409:
                hint = " -- a ModelVersion with this versionTag is already registered"
            raise ModelRegistryError(f"{method} {url} returned HTTP {exc.code} {exc.reason}{hint}") from exc
        except urllib.error.URLError as exc:
            raise ModelRegistryError(f"{method} {url} failed: {exc.reason}. Is the backend running?") from exc

        if not body:
            return None
        try:
            return json.loads(body)
        except json.JSONDecodeError as exc:
            raise ModelRegistryError(f"{method} {url} did not return JSON: {exc}") from exc

    def register(
        self,
        version_tag: str,
        f1_score: float,
        accuracy: Optional[float] = None,
        notes: Optional[str] = None,
        evaluation: Optional[Dict[str, Any]] = None,
        provenance: Optional[Dict[str, Any]] = None,
    ) -> str:
        """``POST /models``. Registers the candidate **inactive**; returns its id.

        ``version_tag`` is ``@unique`` on the backend (see
        ``backend/database/prisma/schema.prisma``, whose comment on
        ``ModelVersion`` says the tag is "auto-generated by AI service") -- so
        this side owns the format. ``pipeline.py`` uses ``v<run-stamp>``,
        e.g. ``v2026-08-17T04-15-33Z``, so a version tag always points back to
        the run directory it came from.

        ``evaluation``/``provenance`` carry the evidence an Admin approval
        requires (see :func:`candidate_evidence`). Re-registering a candidate
        still under review with the *same* artifacts refreshes that evidence;
        different artifacts under the same tag are refused with 409.
        """
        payload: Dict[str, Any] = {"versionTag": version_tag, "f1Score": f1_score}
        if accuracy is not None:
            payload["accuracy"] = accuracy
        if notes is not None:
            payload["notes"] = notes
        if evaluation is not None:
            payload["evaluation"] = evaluation
        if provenance is not None:
            payload["provenance"] = provenance
        result = self._call("/internal/models", "POST", payload)
        model_id = (result or {}).get("id")
        if not model_id:
            raise ModelRegistryError(f"POST {self.base_url}/internal/models did not return an id: {result!r}")
        return model_id

    def activate(self, model_id: str) -> None:
        """Machine credentials cannot promote a model.

        An authenticated administrator must use the admin-only backend route
        after reviewing the candidate; retaining an API-key promotion endpoint
        would recreate broad administrator authorization.
        """
        raise ModelRegistryError(f"Model {model_id} is registered but requires administrator promotion.")

    def get_active(self) -> Optional[dict]:
        """``GET /models/active``. ``None`` when no model has ever been registered.

        Read-only counterpart used by ``service/main.py``'s startup check --
        comparing what the backend thinks is live against the ``version_tag``
        this service is actually serving (``models/<dir>/version.json``).
        """
        return self._call("/internal/models/active", "GET")


class EvidenceError(ValueError):
    """A holdout report or dataset identity cannot back a registration."""


def candidate_provenance(model_dir: str, dataset_version: str, dataset_digest: str) -> Dict[str, Any]:
    """Artifact and training-data identity for a candidate directory.

    ``artifacts`` hashes every file in ``model_dir`` -- the same set the
    serving host verifies against its approval manifest -- so the backend's
    derived bundle digest can later be compared with what ``/health`` reports.
    """
    if not dataset_version.strip():
        raise EvidenceError("a dataset version (the frozen training snapshot) is required")
    if not _SHA256_RE.fullmatch(dataset_digest.lower()):
        raise EvidenceError("the dataset digest must be a SHA-256 hex digest")
    return {
        "artifacts": hash_bundle(model_dir),
        "datasetVersion": dataset_version.strip(),
        "datasetDigest": dataset_digest.lower(),
    }


def holdout_evaluation(report: Dict[str, Any], model_dir: str, artifacts: Dict[str, str]) -> Dict[str, Any]:
    """Convert a ``scripts/evaluate_holdout.py`` report into registry evidence.

    Refuses a report that graded a different checkpoint, drifted inputs, or
    lacks per-class results: an attributable number or none at all.
    """
    version_tag = read_version(model_dir)
    if report.get("version_tag") != version_tag:
        raise EvidenceError(f"the holdout report graded {report.get('version_tag')!r}, not {version_tag!r}")
    if report.get("bundle_digest") and report["bundle_digest"] != bundle_digest(artifacts):
        raise EvidenceError("the holdout report graded different model files than this directory holds")
    if report.get("holdout_integrity") != "ok" or report.get("checkpoint_integrity") != "ok":
        raise EvidenceError(
            "the holdout report was produced with unverified or drifted inputs "
            f"(holdout={report.get('holdout_integrity')}, checkpoint={report.get('checkpoint_integrity')})"
        )
    per_class = report.get("per_class_metrics") or {}
    missing = [label for label in EVIDENCE_CLASSES if label not in per_class]
    if missing or not report.get("holdout_sha256") or not report.get("n_total"):
        raise EvidenceError(f"the holdout report is incomplete (missing: {missing or 'holdout identity'})")
    return {
        "source": "independent_holdout",
        "versionTag": version_tag,
        "macroF1": report["macro_f1"],
        "holdout": {"sha256": report["holdout_sha256"], "rows": report["n_total"]},
        "perClass": {
            label: {key: per_class[label][key] for key in ("support", "precision", "recall", "f1")}
            for label in EVIDENCE_CLASSES
        },
        "evaluatedAt": report.get("evaluated_at"),
    }


def candidate_evidence(
    model_dir: str,
    holdout_report_path: str,
    dataset_version: str,
    dataset_digest: str,
) -> Tuple[float, Dict[str, Any], Dict[str, Any]]:
    """``(f1_score, evaluation, provenance)`` for :meth:`ModelRegistry.register`."""
    with open(holdout_report_path, encoding="utf-8") as handle:
        report = json.load(handle)
    provenance = candidate_provenance(model_dir, dataset_version, dataset_digest)
    evaluation = holdout_evaluation(report, model_dir, provenance["artifacts"])
    return float(evaluation["macroF1"]), evaluation, provenance
